### PR TITLE
Rebase crash_dumper onto current Godot 4.3 master

### PR DESCRIPTION
**Pull request by Chaosed0**
This PR rebases the crash_dumper branch onto Godot's current master branch.

Note that I removed the mono re-hook as it seems to no longer be necessary.

I've only tested this on Windows, as that's the only platform I have available.

### CODE REVIEW

**Comment by Chaosed0** [comment]
The merge conflicts appear to be expected as I chose to rebase rather than merging `master`.

**Comment by hhyyrylainen** [comment]
I'm not sure how merging this should be done...
What did you need to do to rebase this work? I'm kind of guessing that it might be just more effective to redo this crash dumper feature on a clean branch from Godot master and just re-add fresh crash dumper library files and redo the hooking into the engine.

**Comment by fire** [comment]
I remade the branch here. https://github.com/V-Sekai/godot/tree/vsk-crash-dumper-4.3-beta1

**Comment by hhyyrylainen** [comment]
That remade branch looks fine to me based on a quick look. If there is a chance that this feature would finally make it into Godot soon I can probably make some time next week to do some stuff like:
- determining if the signal handler overrides hack is still needed with the dotnet runtime
- updating the breakpad version to latest commit as the previously extracted code is from 2021
- testing that the crash dump generation (and decoding) still works

**Comment by fire** [comment]
Here's my understanding.

1. Godot 4.3 is in beta and in feature freeze
2. I don't know when 4.4 merges, it could be 6 months 4.2 took or it could be the year that 4.3 took.

**Comment by fire** [comment]
Since I want to have crash dumps today. I'll probably revive https://github.com/V-Sekai/godot-sentry-native and use sentry.io (a commercial service).

Edited:

I jammed a golang module for opentelemetry with signoz.

**Comment by Chaosed0** [comment]
I don't mind redoing the work, or simply updating the breakpad integration - it looks relatively simple to do. Primarily, I wanted to update your PR into the Godot engine itself, instead of creating a new PR, so that the history of the conversation would be preserved. It seems that redoing the branch would require me to create a new PR. I'm a new contributor, so it's hard for me to gauge which is the best solution here.

**Comment by Chaosed0** [comment]
A couple more notes:

> testing that the crash dump generation (and decoding) still works

I tested this on windows and it works. I built Godot with debugging symbols and used `OS.crash` to force a crash, which generated a dump file in `%appdata%`. I was able to successfully extract a stack trace from the minidump using Visual Studio.

> determining if the signal handler overrides hack is still needed with the dotnet runtime

The above was done with the dotnet module enabled, and I removed your re-init code in this branch, so I think it is no longer needed.

> updating the breakpad version to latest commit as the previously extracted code is from 2021

I will try to get this done today.

> If there is a chance that this feature would finally make it into Godot soon

To be honest, I have no idea what the chances of this are. I also find it quite demoralizing that critical features necessary for shipping a game like this are missing from the engine, and deprioritized by the maintainers. But I figured if I could add weight to and help out with the issue, perhaps there's a better chance.

**Comment by hhyyrylainen** [comment]
I think what might work is that once you have your branch ready in your fork, I'll pull that to my local git repo and then force reset this repo's `crash_dumper` branch to match your branch, and then push that to github. I have a feeling that that would probably do the correct thing.

**Comment by Chaosed0** [comment]
I've now updated the branch in my fork and tested that it's still functional at least on Windows: https://github.com/Chaosed0/godot-crash-dumper/tree/crash_dumper

Breakpad has been updated from Google's main branch. I removed all the test and HTTP upload files I could find. Here is a list of the new files, in case there are any that I missed that ought to still be removed:

```
 create mode 100644 thirdparty/breakpad/src/client/linux/data/linux-gate-amd.sym
 create mode 100644 thirdparty/breakpad/src/client/linux/data/linux-gate-intel.sym
 create mode 100644 thirdparty/breakpad/src/client/linux/minidump_writer/pe_file.cc
 create mode 100644 thirdparty/breakpad/src/client/linux/minidump_writer/pe_file.h
 create mode 100644 thirdparty/breakpad/src/client/linux/minidump_writer/pe_structs.h
 create mode 100644 thirdparty/breakpad/src/client/mac/UnitTests-Info.plist
 create mode 100644 thirdparty/breakpad/src/client/mac/handler/minidump_test.xcodeproj/project.pbxproj
 create mode 100644 thirdparty/breakpad/src/client/mac/handler/minidump_tests32-Info.plist
 create mode 100644 thirdparty/breakpad/src/client/mac/handler/minidump_tests64-Info.plist
 create mode 100644 thirdparty/breakpad/src/client/mac/handler/obj-cTestCases-Info.plist
 create mode 100644 thirdparty/breakpad/src/client/solaris/handler/exception_handler_test.cc
 create mode 100644 thirdparty/breakpad/src/common/dwarf/dwarf2reader_test_common.h
 create mode 100644 thirdparty/breakpad/src/common/dwarf/elf_reader.cc
 create mode 100644 thirdparty/breakpad/src/common/dwarf/elf_reader.h
 create mode 100644 thirdparty/breakpad/src/common/linux/dump_symbols.cc
 create mode 100644 thirdparty/breakpad/src/common/linux/dump_symbols.h
 create mode 100644 thirdparty/breakpad/src/common/linux/scoped_pipe.cc
 create mode 100644 thirdparty/breakpad/src/common/linux/scoped_pipe.h
 create mode 100644 thirdparty/breakpad/src/common/linux/scoped_tmpfile.cc
 create mode 100644 thirdparty/breakpad/src/common/linux/scoped_tmpfile.h
 create mode 100644 thirdparty/breakpad/src/common/linux/symbol_collector_client.cc
 create mode 100644 thirdparty/breakpad/src/common/linux/symbol_collector_client.h
 create mode 100644 thirdparty/breakpad/src/common/linux/synth_elf.cc
 create mode 100644 thirdparty/breakpad/src/common/linux/synth_elf.h
 create mode 100644 thirdparty/breakpad/src/common/mac/SymbolCollectorClient.h
 create mode 100644 thirdparty/breakpad/src/common/mac/SymbolCollectorClient.m
 create mode 100644 thirdparty/breakpad/src/common/mac/dump_syms.cc
 create mode 100644 thirdparty/breakpad/src/common/mac/dump_syms.h
 create mode 100644 thirdparty/breakpad/src/common/safe_math.h
 create mode 100644 thirdparty/breakpad/src/common/solaris/dump_symbols.cc
 create mode 100644 thirdparty/breakpad/src/common/solaris/dump_symbols.h
 create mode 100644 thirdparty/breakpad/src/common/test_assembler.cc
 create mode 100644 thirdparty/breakpad/src/common/test_assembler.h
 create mode 100644 thirdparty/breakpad/src/common/windows/symbol_collector_client.cc
 create mode 100644 thirdparty/breakpad/src/common/windows/symbol_collector_client.h
 create mode 100644 thirdparty/breakpad/src/google_breakpad/common/minidump_cpu_riscv.h
```

**Comment by hhyyrylainen** [comment]
I have a feeling that at least the following are data files that should not be included:
```
 create mode 100644 thirdparty/breakpad/src/client/linux/data/linux-gate-amd.sym
 create mode 100644 thirdparty/breakpad/src/client/linux/data/linux-gate-intel.sym
```

Also these might be data generation only files that may not be needed for a stripped down client library compilation:
```
 create mode 100644 thirdparty/breakpad/src/client/mac/handler/minidump_test.xcodeproj/project.pbxproj
 create mode 100644 thirdparty/breakpad/src/client/mac/handler/minidump_tests32-Info.plist
 create mode 100644 thirdparty/breakpad/src/client/mac/handler/minidump_tests64-Info.plist
 create mode 100644 thirdparty/breakpad/src/client/mac/handler/obj-cTestCases-Info.plist
 create mode 100644 thirdparty/breakpad/src/client/solaris/handler/exception_handler_test.cc
create mode 100644 thirdparty/breakpad/src/common/dwarf/dwarf2reader_test_common.h
 create mode 100644 thirdparty/breakpad/src/common/dwarf/elf_reader.cc
 create mode 100644 thirdparty/breakpad/src/common/dwarf/elf_reader.h
 create mode 100644 thirdparty/breakpad/src/common/linux/dump_symbols.cc
 create mode 100644 thirdparty/breakpad/src/common/linux/dump_symbols.h
 create mode 100644 thirdparty/breakpad/src/common/mac/dump_syms.cc
 create mode 100644 thirdparty/breakpad/src/common/mac/dump_syms.h
 create mode 100644 thirdparty/breakpad/src/common/safe_math.h
 create mode 100644 thirdparty/breakpad/src/common/solaris/dump_symbols.cc
 create mode 100644 thirdparty/breakpad/src/common/solaris/dump_symbols.h
 create mode 100644 thirdparty/breakpad/src/common/test_assembler.cc
 create mode 100644 thirdparty/breakpad/src/common/test_assembler.h
 create mode 100644 thirdparty/breakpad/src/common/windows/symbol_collector_client.cc
 create mode 100644 thirdparty/breakpad/src/common/windows/symbol_collector_client.h
```

Some of those might be necessary, but I think at least some of those source files are purely for the dumping side of things or just tests, meaning that they are unnecessary to include with the godot engine. Though to be sure each platform's files should be inspected to see if some other headers include those files to be removed to do a sanity check on not removing important files. I should be able to also pretty easily test on Linux to make sure there aren't missing files that prevent compilation.

**Comment by Chaosed0** [comment]
Removed those files and re-tested, and things appear to still work.

Also did a cursory search on the files for includes of those files, and it appears that they're unused, so I think we're good there.

**Comment by hhyyrylainen** [comment]
I found a few problems compiling on Linux, but I fixed those. The PR to Godot should now be updated (based on force resetting to your version of this branch).

**Comment by Chaosed0** [comment]
Excellent, thanks for doing so. I'll keep an eye on the pull request, hopefully we can get it in!

**Pull request merged**
